# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1eb3a6e9568aab5e2e5ffc3be8d810663b577cf49bb9179212f67995c88eeb5d2ac42f1ba237733b2c258bfd3847d2ea28a7ef0c3b4d566386ed97172399544c

test:
  secret_key_base: a82aa510b04d4904ccd82f8ff74e09f3bba21be01412fe5614282fff69c3f2009ffae64f1a4257df96d9f82cb7934802853ccc781945d68ea2219988e574b055

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
